#include<bits/stdc++.h>
using namespace std;
int main()
{
    int i,n,m,k,x=0,y,j,diag=0,non_diag=0,total=0,t=0;
    scanf("%d",&t);
    int ar[t];
    for(i=0; i<t; i++)
    {
        scanf("%d %d %d",&n,&m,&k);
        x=0;
        if(n==m)
        {
            diag=n;
            y=n;
            non_diag=0;
            j=0;
            if(diag==k)
            {
                ar[i]=diag;
                continue;
            }
            else
            {
                while(non_diag<k)
                {
                    x=0;
                    if(diag!=0)
                    {
                        diag--;
                        non_diag=non_diag+2;
                    }
                    else
                        non_diag=non_diag+1;
                    total=diag+non_diag;
                    if(total==k)
                    {
                        if(diag==0)
                        {
                            total=0;
                            diag=y;
                            non_diag=j;
                            while(total!=k)
                            {
                                diag=diag+1;
                                total=diag+non_diag;
                            }
                            ar[i]=diag;
                            x=1;
                            break;
                        }
                        else
                        {
                            ar[i]=diag;
                            x=1;
                            break;
                        }
                    }
                }
                if(x==1)
                    continue;
                else if(x==0)
                {
                    ar[i]=-1;
                    continue;
                }
            }
        }
        else
        {
            if(n>m)
            {
                diag=m;
                y=m;
                non_diag=n-m;
                j=n-m;
                total=diag+non_diag;
            }
            else
            {
                diag=n;
                y=n;
                non_diag=m-n;
                j=m-n;
                total=diag+non_diag;
            }
            if(total==k)
            {
                ar[i]=diag;
                continue;
            }
            else
            {
                while(non_diag<k)
                {
                    x=0;
                    if(diag!=0)
                    {
                        diag--;
                        non_diag=non_diag+2;
                    }
                    else
                        non_diag=non_diag+1;
                    total=diag+non_diag;
                    if(total==k)
                    {
                        if(diag==0)
                        {
                            total=0;
                            diag=y;
                            non_diag=j;
                            while(total!=k)
                            {
                                diag=diag+1;
                                total=diag+non_diag;
                            }
                            ar[i]=diag;
                            x=1;
                            break;
                        }
                        else
                        {
                            ar[i]=diag;
                            x=1;
                            break;
                        }
                    }
                }
                if(x==1)
                    continue;
                else if(x==0)
                {
                    ar[i]=-1;
                    continue;
                }
            }
        }
    }
    for(i=0; i<t; i++)
    {
        printf("%d\n",ar[i]);
    }
    return 0;
}
